version: "3.8"

services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
    networks:
      - app-network

  mongo:
    container_name: mongo-database
    image: mongo
    # restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: usersdb
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: none
    networks:
      - app-network
    logging:
      driver: "none"

  users:
    container_name: users-express
    build:
      context: ./users
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/usersdb?authSource=admin
    volumes:
      - ./users:/app/users
    depends_on:
      - mongo

volumes:
  mongodb-data:

networks:
  app-network:
