version: "3.8"

services:
  users:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000

  pictures:
    build:
      context: ./pictures
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
