version: "3.8"

services:
  users:
    container_name: users-flask
    build:
      context: ./users
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./users:/app/users
    networks:
      - picturely-network
    command: flask run --host=0.0.0.0

  pictures:
    container_name: pictures-express
    build:
      context: ./pictures
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    volumes:
      - ./pictures:/app/pictures
    networks:
      - picturely-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
      - pictures
    networks:
      - picturely-network

networks:
  picturely-network:
