version: "3.8"

services:
  # users flask microservice
  users:
    container_name: users-flask
    build:
      context: ./users
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:5000"
    depends_on:
      - users-db
    environment:
      PORT: 8001
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/usersdatabase
    volumes:
      - ./users:/app/users
    networks:
      - picturely-network
    command: flask run --host=0.0.0.0

  users-db:
    image: postgres
    container_name: users-postgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdatabase
    volumes:
      - db-data:/var/lib/postgresql/data

  # # media express microservice
  # media:
  #   container_name: media-express
  #   build:
  #     context: ./media
  #     dockerfile: ./Dockerfile.dev
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     PORT: 8000
  #   volumes:
  #     - ./media:/app/media
  #   networks:
  #     - picturely-network
  #
  # # posts express microservice
  # posts:
  #   container_name: posts-gin
  #   build:
  #     context: ./posts
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./posts:/app/posts
  #   environment:
  #     GIN_MODE: debug
  #     PORT: 8080
  #   networks:
  #     - picturely-network

  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
      # - media
    networks:
      - picturely-network

volumes:
  db-data:

networks:
  picturely-network:
