version: "3.8"

services:
  # users flask microservice
  users:
    container_name: users-flask
    build:
      context: ./users
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - users-db
    environment:
      PORT: 5000
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/usersdatabase
    volumes:
      - ./users:/app/users
    networks:
      - picturely-network
    command: flask run --host=0.0.0.0

  users-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdatabase
    volumes:
      - db-data:/var/lib/postgresql/data

  # pictures express microservice
  pictures:
    container_name: pictures-express
    build:
      context: ./pictures
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    volumes:
      - ./pictures:/app/pictures
    networks:
      - picturely-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
      - pictures
    networks:
      - picturely-network

volumes:
  db-data:

networks:
  picturely-network:
