version: "3.8"

services:
  # # users express microservice
  users:
    container_name: users-express
    build:
      context: ./users
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/users-db
    volumes:
      - ./users:/app/users
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: users-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
